# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: WayveScenes101 Benchmark Challenge
short_description: A benchmark for evaluating novel view synthesis methods on diverse and challenging real-world driving scenes 
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard listing all valid submissions
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2024-06-01 00:00:00
end_date: 2029-12-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["PSNR", "SSIM", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "PSNR": {
            "sort_ascending": True,
            "description": "Peak Signal-to-Noise Ratio (PSNR) is a metric that measures the quality of an image by comparing it to a reference image. The metric is expressed in decibels (dB) and higher values indicate better quality.",
          },
          "SSIM": {
            "sort_ascending": True,
            "description": "Structural Similarity Index (SSIM) is a metric that measures the similarity between two images. The SSIM score ranges from -1 to 1, where 1 indicates perfect similarity between the images.",
          },
          "Total": {
            "sort_ascending": True,
            "description": "The total score is calculated as the average of the PSNR and SSIM scores. For more details, refer to the evaluation script for the exact formula used to calculate the total.",
          },
        }
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2024-05-01 00:00:00
    end_date: 2029-12-31 23:59:59
    test_annotation_file: annotations/wayve_scenes_101.zip
    codename: dev
    max_submissions_per_day: 50
    max_submissions_per_month: 500
    max_submissions: 500
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: Have you read the terms and conditions?
        description: You cannot participate in the challenge if you have not read the terms and conditions
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".zip, .jpg, .png, .jpeg"
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-05-01 00:00:00
    end_date: 2029-12-31 23:59:59
    test_annotation_file: annotations/wayve_scene_reconstruction_benchmark.zip
    codename: test
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
      - name: Have you read the Terms and Conditions?
        description: You cannot participate in the challenge if you have not read the terms and conditions.
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
